##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
# AUTHOR		: Throughc
##############################################################################
# VERSION&DATE	: Version 1.00	2007/12/25 (Throughc)
##############################################################################

ifeq ($(X_PLATFORM_TARGET),SHW-M110S)
LOCAL_CFLAGS += -DM110S=true
endif

ifeq ($(X_PLATFORM_TARGET),SHW-M115S)
LOCAL_CFLAGS += -DM115S=true
endif

obj-$(CONFIG_COMPASS_YAMAHA)	+= yamaha.o
